export interface DemoTicket {
    id: string;
    code: string;
    title: string;
    status: 'open' | 'closed' | 'reopened';
    client: string;
    clientEn: string;
    company: string;
    companyEn: string;
    assignedResource: string | null;
    assignedResourceEn: string | null;
    month: 'Nov' | 'Dec' | 'Jan' | 'Feb' | 'Mar' | 'Apr';
}

export const MONTH_ORDER: Array<'Nov' | 'Dec' | 'Jan' | 'Feb' | 'Mar' | 'Apr'> = [
    'Nov',
    'Dec',
    'Jan',
    'Feb',
    'Mar',
    'Apr',
];

export const MONTH_LABELS: Record<'Nov' | 'Dec' | 'Jan' | 'Feb' | 'Mar' | 'Apr', { en: string; ar: string }> = {
    Nov: { en: 'Nov 2025', ar: 'نوفمبر ٢٠٢٥' },
    Dec: { en: 'Dec 2025', ar: 'ديسمبر ٢٠٢٥' },
    Jan: { en: 'Jan 2026', ar: 'يناير ٢٠٢٦' },
    Feb: { en: 'Feb 2026', ar: 'فبراير ٢٠٢٦' },
    Mar: { en: 'Mar 2026', ar: 'مارس ٢٠٢٦' },
    Apr: { en: 'Apr 2026', ar: 'أبريل ٢٠٢٦' },
};

export const MOCK_TICKETS: DemoTicket[] = [
    // --- November 2025 (10 tickets: 3 Open, 6 Closed, 1 Reopened) ---
    {
        id: 'tck-01',
        code: 'TCK-2025-101',
        title: 'طلب تفعيل ربط بوابة مقيم الإلكترونية',
        status: 'open',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Nov',
    },
    {
        id: 'tck-02',
        code: 'TCK-2025-102',
        title: 'استفسار بشأن اشتراك منصة قوى السنوي',
        status: 'open',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Nov',
    },
    {
        id: 'tck-03',
        code: 'TCK-2025-103',
        title: 'خلل في مزامنة بيانات السجل التجاري',
        status: 'open',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Nov',
    },
    {
        id: 'tck-04',
        code: 'TCK-2025-104',
        title: 'إصدار شهادة التوطين والمواءمة',
        status: 'closed',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Nov',
    },
    {
        id: 'tck-05',
        code: 'TCK-2025-105',
        title: 'تجديد ترخيص الاستثمار الأجنبي',
        status: 'closed',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Nov',
    },
    {
        id: 'tck-06',
        code: 'TCK-2025-106',
        title: 'تعديل الصلاحيات الإدارية على منصة بلدي',
        status: 'closed',
        client: 'نورة الغامدي',
        clientEn: 'Noura Al-Ghamdi',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Nov',
    },
    {
        id: 'tck-07',
        code: 'TCK-2025-107',
        title: 'سداد رسوم المقابل المالي للرخص المهنية',
        status: 'closed',
        client: 'سلطان الحربي',
        clientEn: 'Sultan Al-Harbi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Nov',
    },
    {
        id: 'tck-08',
        code: 'TCK-2025-108',
        title: 'تحديث بيانات المفوض بالتوقيع في الغرفة التجارية',
        status: 'closed',
        client: 'ريم الشهري',
        clientEn: 'Reem Al-Shehri',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Nov',
    },
    {
        id: 'tck-09',
        code: 'TCK-2025-109',
        title: 'طباعة شهادة الزكاة وضريبة الدخل',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Nov',
    },
    {
        id: 'tck-10',
        code: 'TCK-2025-110',
        title: 'طلب إعادة فحص مستندات الإلغاء بالسجل التجاري',
        status: 'reopened',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Nov',
    },

    // --- December 2025 (12 tickets: 4 Open, 7 Closed, 1 Reopened) ---
    {
        id: 'tck-11',
        code: 'TCK-2025-111',
        title: 'إلغاء تأشيرة خروج وعودة غير مستخدمة',
        status: 'open',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Dec',
    },
    {
        id: 'tck-12',
        code: 'TCK-2025-112',
        title: 'إضافة فرع جديد للمنشأة في التأمينات',
        status: 'open',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Dec',
    },
    {
        id: 'tck-13',
        code: 'TCK-2025-113',
        title: 'طلب ربط الحساب البنكي لنظام حماية الأجور',
        status: 'open',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Dec',
    },
    {
        id: 'tck-14',
        code: 'TCK-2025-114',
        title: 'تأكيد صحة عقد العمل الإلكتروني',
        status: 'open',
        client: 'نورة الغامدي',
        clientEn: 'Noura Al-Ghamdi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Dec',
    },
    {
        id: 'tck-15',
        code: 'TCK-2025-115',
        title: 'تحديث هوية مقيم لموظفي المشاريع',
        status: 'closed',
        client: 'سلطان الحربي',
        clientEn: 'Sultan Al-Harbi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Dec',
    },
    {
        id: 'tck-16',
        code: 'TCK-2025-116',
        title: 'تعديل الاسم التجاري المسجل باللغة الإنجليزية',
        status: 'closed',
        client: 'ريم الشهري',
        clientEn: 'Reem Al-Shehri',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Dec',
    },
    {
        id: 'tck-17',
        code: 'TCK-2025-117',
        title: 'تفعيل ملف المنشأة لدى وزارة التجارة',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Dec',
    },
    {
        id: 'tck-18',
        code: 'TCK-2025-118',
        title: 'استرداد مبالغ سداد مقيم المعلقة',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Dec',
    },
    {
        id: 'tck-19',
        code: 'TCK-2025-119',
        title: 'نقل خدمات وافد بموافقة المنشأة السابقة',
        status: 'closed',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Dec',
    },
    {
        id: 'tck-20',
        code: 'TCK-2025-120',
        title: 'إصدار تصريح عمل لموظف تحت التدريب',
        status: 'closed',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Dec',
    },
    {
        id: 'tck-21',
        code: 'TCK-2025-121',
        title: 'تحميل بيان الرواتب الشهري في مدد',
        status: 'closed',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Dec',
    },
    {
        id: 'tck-22',
        code: 'TCK-2025-122',
        title: 'اعتراض على مخالفة تأخير توثيق العقود',
        status: 'reopened',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Dec',
    },

    // --- January 2026 (11 tickets: 5 Open, 5 Closed, 1 Reopened) ---
    {
        id: 'tck-23',
        code: 'TCK-2026-001',
        title: 'طلب ترقية الباقة الشهرية للبوابة الرقمية',
        status: 'open',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Jan',
    },
    {
        id: 'tck-24',
        code: 'TCK-2026-002',
        title: 'تسجيل الدخول الموحد عبر النفاذ الوطني',
        status: 'open',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Jan',
    },
    {
        id: 'tck-25',
        code: 'TCK-2026-003',
        title: 'حساب نسبة التوطين في نطاقات',
        status: 'open',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Jan',
    },
    {
        id: 'tck-26',
        code: 'TCK-2026-004',
        title: 'تعديل نشاط السجل الفرعي في جدة',
        status: 'open',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Jan',
    },
    {
        id: 'tck-27',
        code: 'TCK-2026-005',
        title: 'طلب تمديد تأشيرة زيارة العمل للخبراء',
        status: 'open',
        client: 'نورة الغامدي',
        clientEn: 'Noura Al-Ghamdi',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Jan',
    },
    {
        id: 'tck-28',
        code: 'TCK-2026-006',
        title: 'شهادة الالتزام بحماية الأجور للربع الأخير',
        status: 'closed',
        client: 'سلطان الحربي',
        clientEn: 'Sultan Al-Harbi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Jan',
    },
    {
        id: 'tck-29',
        code: 'TCK-2026-007',
        title: 'إلغاء بلاغ تغيب بعد المصالحة الودية',
        status: 'closed',
        client: 'ريم الشهري',
        clientEn: 'Reem Al-Shehri',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Jan',
    },
    {
        id: 'tck-30',
        code: 'TCK-2026-008',
        title: 'إصدار تصريح الدفاع المدني للمستودعات',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Jan',
    },
    {
        id: 'tck-31',
        code: 'TCK-2026-009',
        title: 'تحديث بيانات الحساب في منصة سابر',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Jan',
    },
    {
        id: 'tck-32',
        code: 'TCK-2026-010',
        title: 'طلب تفويض إلكتروني لمعاملات المرور',
        status: 'closed',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Jan',
    },
    {
        id: 'tck-33',
        code: 'TCK-2026-011',
        title: 'استئناف قرار التقييم الضريبي في هيئة الزكاة',
        status: 'reopened',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Jan',
    },

    // --- February 2026 (11 tickets: 5 Open, 6 Closed, 0 Reopened) ---
    {
        id: 'tck-34',
        code: 'TCK-2026-012',
        title: 'تفعيل خدمة التحقق من العنوان الوطني للمنشأة',
        status: 'open',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Feb',
    },
    {
        id: 'tck-35',
        code: 'TCK-2026-013',
        title: 'فحص استحقاق دعم صندوق الموارد البشرية (هدف)',
        status: 'open',
        client: 'نورة الغامدي',
        clientEn: 'Noura Al-Ghamdi',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Feb',
    },
    {
        id: 'tck-36',
        code: 'TCK-2026-014',
        title: 'تسوية مبالغ غرامات التأخير في التأمينات',
        status: 'open',
        client: 'سلطان الحربي',
        clientEn: 'Sultan Al-Harbi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Feb',
    },
    {
        id: 'tck-37',
        code: 'TCK-2026-015',
        title: 'تعديل البريد الإلكتروني المعتمد في سداد',
        status: 'open',
        client: 'ريم الشهري',
        clientEn: 'Reem Al-Shehri',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Feb',
    },
    {
        id: 'tck-38',
        code: 'TCK-2026-016',
        title: 'إصدار بطاقة تشغيل مركبات النقل الثقيل',
        status: 'open',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Feb',
    },
    {
        id: 'tck-39',
        code: 'TCK-2026-017',
        title: 'تحديث بيانات شهادة الآيزو المعتمدة',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Feb',
    },
    {
        id: 'tck-40',
        code: 'TCK-2026-018',
        title: 'استخراج بدل فاقد لشهادة رخصة البلدية',
        status: 'closed',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Feb',
    },
    {
        id: 'tck-41',
        code: 'TCK-2026-019',
        title: 'توثيق لائحة تنظيم العمل الداخلية',
        status: 'closed',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Feb',
    },
    {
        id: 'tck-42',
        code: 'TCK-2026-020',
        title: 'إلغاء تسجيل المنشأة لدى مصلحة الزكاة للفرع القديم',
        status: 'closed',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Feb',
    },
    {
        id: 'tck-43',
        code: 'TCK-2026-021',
        title: 'تجديد شهادة عضوية الغرفة التجارية',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Feb',
    },
    {
        id: 'tck-44',
        code: 'TCK-2026-022',
        title: 'ربط بيانات المشتركين مع منصة صحتي',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Feb',
    },

    // --- March 2026 (11 tickets: 6 Open, 4 Closed, 1 Reopened) ---
    {
        id: 'tck-45',
        code: 'TCK-2026-023',
        title: 'مشكلة في تحميل ملف حماية الأجور بصيغة SIF',
        status: 'open',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Mar',
    },
    {
        id: 'tck-46',
        code: 'TCK-2026-024',
        title: 'طلب تقسيط المستحقات الزكوية المتبقية',
        status: 'open',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Mar',
    },
    {
        id: 'tck-47',
        code: 'TCK-2026-025',
        title: 'استكمال بيانات المساهمين في السجل التجاري',
        status: 'open',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Mar',
    },
    {
        id: 'tck-48',
        code: 'TCK-2026-026',
        title: 'طلب تمديد مهلة تعديل الأوضاع في منصة قوى',
        status: 'open',
        client: 'نورة الغامدي',
        clientEn: 'Noura Al-Ghamdi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Mar',
    },
    {
        id: 'tck-49',
        code: 'TCK-2026-027',
        title: 'تعديل البريد الرسمي لمستلمي إشعارات الحساب',
        status: 'open',
        client: 'سلطان الحربي',
        clientEn: 'Sultan Al-Harbi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Mar',
    },
    {
        id: 'tck-50',
        code: 'TCK-2026-028',
        title: 'فحص توافق أرقام الآيبان للتحويلات الحكومية',
        status: 'open',
        client: 'ريم الشهري',
        clientEn: 'Reem Al-Shehri',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Mar',
    },
    {
        id: 'tck-51',
        code: 'TCK-2026-029',
        title: 'تحديث اشتراك مقيم لفرع الدمام',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Mar',
    },
    {
        id: 'tck-52',
        code: 'TCK-2026-030',
        title: 'إنشاء حساب مستخدم إداري للمدير المالي',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Mar',
    },
    {
        id: 'tck-53',
        code: 'TCK-2026-031',
        title: 'إصدار تصريح عمل للمهندسين الاستشاريين',
        status: 'closed',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Mar',
    },
    {
        id: 'tck-54',
        code: 'TCK-2026-032',
        title: 'تأكيد سلامة شهادة المنشأ للبضائع',
        status: 'closed',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Mar',
    },
    {
        id: 'tck-55',
        code: 'TCK-2026-033',
        title: 'إعادة فتح تذكرة مطابقة الرصيد التأميني بعد التحديث',
        status: 'reopened',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Mar',
    },

    // --- April 2026 (9 tickets: 5 Open, 3 Closed, 1 Reopened) ---
    {
        id: 'tck-56',
        code: 'TCK-2026-034',
        title: 'طلب إضافة مستخدم جديد لصلاحية سداد الفواتير',
        status: 'open',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Apr',
    },
    {
        id: 'tck-57',
        code: 'TCK-2026-035',
        title: 'تأخر وصول رمز التحقق عبر أبشر أعمال',
        status: 'open',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Apr',
    },
    {
        id: 'tck-58',
        code: 'TCK-2026-036',
        title: 'طلب استشارة بخصوص نظام المعاملات المدنية',
        status: 'open',
        client: 'محمد العتيبي',
        clientEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Apr',
    },
    {
        id: 'tck-59',
        code: 'TCK-2026-037',
        title: 'مراجعة عقود العمل الموسمية في موسم الحج والعمرة',
        status: 'open',
        client: 'خالد المطيري',
        clientEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Apr',
    },
    {
        id: 'tck-60',
        code: 'TCK-2026-038',
        title: 'طلب تفعيل واجهة برمجة التطبيقات (API) لمنصة عون',
        status: 'open',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedResource: null,
        assignedResourceEn: null,
        month: 'Apr',
    },
    {
        id: 'tck-61',
        code: 'TCK-2026-039',
        title: 'إنهاء إجراءات شطب السجل التجاري لفرع الخبر',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'عمر الدوسري',
        assignedResourceEn: 'Omar Al-Dossary',
        month: 'Apr',
    },
    {
        id: 'tck-62',
        code: 'TCK-2026-040',
        title: 'استرداد مبالغ التعويض المالي عن الإجازات',
        status: 'closed',
        client: 'سارة الشمري',
        clientEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedResource: 'م. كريم وجدي',
        assignedResourceEn: 'Eng. Karim Wagdi',
        month: 'Apr',
    },
    {
        id: 'tck-63',
        code: 'TCK-2026-041',
        title: 'تأكيد سريان رخصة الدفاع المدني المركزية',
        status: 'closed',
        client: 'عبدالله القحطاني',
        clientEn: 'Abdullah Al-Qahtani',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedResource: 'فاطمة عبدالفتاح',
        assignedResourceEn: 'Fatima Abdelfattah',
        month: 'Apr',
    },
    {
        id: 'tck-64',
        code: 'TCK-2026-042',
        title: 'طلب إعادة تدقيق مطابقة حساب المنشأة لدى مدد',
        status: 'reopened',
        client: 'فهد الدوسري',
        clientEn: 'Fahad Al-Dossary',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedResource: 'أحمد السالم',
        assignedResourceEn: 'Ahmed Al-Salem',
        month: 'Apr',
    },
];

export interface TableTicket {
    id: string;
    ticketId: string;
    subject: string;
    subjectEn: string;
    ticketType: string;
    ticketTypeEn: string;
    customer: string;
    customerEn: string;
    company: string;
    companyEn: string;
    assignedTo: string | null;
    assignedToEn: string | null;
    assignedBy: string;
    assignedByEn: string;
    replyStatus: 'replied' | 'waiting_customer' | 'pending_agent';
    status: 'open' | 'closed' | 'reopened';
    closedDate: string | null;
    priority: 'High' | 'Medium' | 'Low';
    createdDate: string;
}

export const DEMO_TABLE_TICKETS: TableTicket[] = [
    {
        id: 'tb-01',
        ticketId: 'TCK-2026-001',
        subject: 'طلب تفعيل ربط بوابة مقيم الإلكترونية',
        subjectEn: 'Muqeem API gateway activation request',
        ticketType: 'الدعم الفني',
        ticketTypeEn: 'Technical Support',
        customer: 'عبدالله القحطاني',
        customerEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'replied',
        status: 'open',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-03-24',
    },
    {
        id: 'tb-02',
        ticketId: 'TCK-2026-002',
        subject: 'استفسار بشأن اشتراك منصة قوى السنوي',
        subjectEn: 'Qiwa annual platform subscription inquiry',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'سارة الشمري',
        customerEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'waiting_customer',
        status: 'open',
        closedDate: null,
        priority: 'Medium',
        createdDate: '2026-03-22',
    },
    {
        id: 'tb-03',
        ticketId: 'TCK-2026-003',
        subject: 'خلل في مزامنة بيانات السجل التجاري',
        subjectEn: 'Commercial Registration sync failure',
        ticketType: 'الدعم الفني',
        ticketTypeEn: 'Technical Support',
        customer: 'محمد العتيبي',
        customerEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedTo: null,
        assignedToEn: null,
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'pending_agent',
        status: 'open',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-03-21',
    },
    {
        id: 'tb-04',
        ticketId: 'TCK-2026-004',
        subject: 'إصدار شهادة التوطين والمواءمة',
        subjectEn: 'Saudization & alignment certificate issuance',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'خالد المطيري',
        customerEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedTo: 'فاطمة عبدالفتاح',
        assignedToEn: 'Fatima Abdelfattah',
        assignedBy: 'م. كريم وجدي',
        assignedByEn: 'Eng. Karim Wagdi',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-25',
        priority: 'Medium',
        createdDate: '2026-03-18',
    },
    {
        id: 'tb-05',
        ticketId: 'TCK-2026-005',
        subject: 'تجديد ترخيص الاستثمار الأجنبي',
        subjectEn: 'Foreign investment license renewal request',
        ticketType: 'استفسار امتثال',
        ticketTypeEn: 'Compliance Inquiry',
        customer: 'فهد الدوسري',
        customerEn: 'Fahad Al-Dossary',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedTo: 'عمر الدوسري',
        assignedToEn: 'Omar Al-Dossary',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-23',
        priority: 'High',
        createdDate: '2026-03-15',
    },
    {
        id: 'tb-06',
        ticketId: 'TCK-2026-006',
        subject: 'تعديل الصلاحيات الإدارية على منصة بلدي',
        subjectEn: 'Balady portal admin permission adjustment',
        ticketType: 'الدعم الفني',
        ticketTypeEn: 'Technical Support',
        customer: 'نورة الغامدي',
        customerEn: 'Noura Al-Ghamdi',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-20',
        priority: 'Low',
        createdDate: '2026-03-14',
    },
    {
        id: 'tb-07',
        ticketId: 'TCK-2026-007',
        subject: 'سداد رسوم المقابل المالي للرخص المهنية',
        subjectEn: 'Professional license financial levy settlement',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'سلطان الحربي',
        customerEn: 'Sultan Al-Harbi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-19',
        priority: 'Medium',
        createdDate: '2026-03-12',
    },
    {
        id: 'tb-08',
        ticketId: 'TCK-2026-008',
        subject: 'تحديث بيانات المفوض بالتوقيع في الغرفة التجارية',
        subjectEn: 'Chamber of commerce signatory update',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'ريم الشهري',
        customerEn: 'Reem Al-Shehri',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedTo: 'فاطمة عبدالفتاح',
        assignedToEn: 'Fatima Abdelfattah',
        assignedBy: 'م. كريم وجدي',
        assignedByEn: 'Eng. Karim Wagdi',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-17',
        priority: 'Low',
        createdDate: '2026-03-11',
    },
    {
        id: 'tb-09',
        ticketId: 'TCK-2026-009',
        subject: 'طباعة شهادة الزكاة وضريبة الدخل',
        subjectEn: 'Zakat & income tax certificate export',
        ticketType: 'استفسار امتثال',
        ticketTypeEn: 'Compliance Inquiry',
        customer: 'عبدالله القحطاني',
        customerEn: 'Abdullah Al-Qahtani',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedTo: 'عمر الدوسري',
        assignedToEn: 'Omar Al-Dossary',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-16',
        priority: 'Low',
        createdDate: '2026-03-10',
    },
    {
        id: 'tb-10',
        ticketId: 'TCK-2026-010',
        subject: 'طلب إعادة فحص مستندات الإلغاء بالسجل التجاري',
        subjectEn: 'CR cancellation document re-examination request',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'سارة الشمري',
        customerEn: 'Sarah Al-Shammari',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'pending_agent',
        status: 'reopened',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-03-08',
    },
    {
        id: 'tb-11',
        ticketId: 'TCK-2026-011',
        subject: 'إلغاء تأشيرة خروج وعودة غير مستخدمة',
        subjectEn: 'Unused exit re-entry visa cancellation',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'محمد العتيبي',
        customerEn: 'Mohammed Al-Otaibi',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'waiting_customer',
        status: 'open',
        closedDate: null,
        priority: 'Medium',
        createdDate: '2026-03-06',
    },
    {
        id: 'tb-12',
        ticketId: 'TCK-2026-012',
        subject: 'إضافة فرع جديد للمنشأة في التأمينات',
        subjectEn: 'Add new establishment branch in GOSI',
        ticketType: 'استفسار امتثال',
        ticketTypeEn: 'Compliance Inquiry',
        customer: 'خالد المطيري',
        customerEn: 'Khalid Al-Mutairi',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedTo: null,
        assignedToEn: null,
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'pending_agent',
        status: 'open',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-03-05',
    },
    {
        id: 'tb-13',
        ticketId: 'TCK-2026-013',
        subject: 'طلب ربط الحساب البنكي لنظام حماية الأجور',
        subjectEn: 'Bank account connection for WPS',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'فهد الدوسري',
        customerEn: 'Fahad Al-Dossary',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedTo: 'فاطمة عبدالفتاح',
        assignedToEn: 'Fatima Abdelfattah',
        assignedBy: 'م. كريم وجدي',
        assignedByEn: 'Eng. Karim Wagdi',
        replyStatus: 'replied',
        status: 'open',
        closedDate: null,
        priority: 'Medium',
        createdDate: '2026-03-04',
    },
    {
        id: 'tb-14',
        ticketId: 'TCK-2026-014',
        subject: 'تأكيد صحة عقد العمل الإلكتروني',
        subjectEn: 'Electronic employment contract validation',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'نورة الغامدي',
        customerEn: 'Noura Al-Ghamdi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedTo: 'عمر الدوسري',
        assignedToEn: 'Omar Al-Dossary',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'waiting_customer',
        status: 'open',
        closedDate: null,
        priority: 'Low',
        createdDate: '2026-03-02',
    },
    {
        id: 'tb-15',
        ticketId: 'TCK-2026-015',
        subject: 'تحديث هوية مقيم لموظفي المشاريع',
        subjectEn: 'Project personnel Muqeem ID update',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'سلطان الحربي',
        customerEn: 'Sultan Al-Harbi',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-12',
        priority: 'Medium',
        createdDate: '2026-02-28',
    },
    {
        id: 'tb-16',
        ticketId: 'TCK-2026-016',
        subject: 'تعديل الاسم التجاري المسجل باللغة الإنجليزية',
        subjectEn: 'Registered English trade name amendment',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'ريم الشهري',
        customerEn: 'Reem Al-Shehri',
        company: 'شركة علم لأمن المعلومات',
        companyEn: 'Elm Info Security',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-08',
        priority: 'Low',
        createdDate: '2026-02-26',
    },
    {
        id: 'tb-17',
        ticketId: 'TCK-2026-017',
        subject: 'تفعيل ملف المنشأة لدى وزارة التجارة',
        subjectEn: 'Ministry of Commerce establishment file activation',
        ticketType: 'استفسار امتثال',
        ticketTypeEn: 'Compliance Inquiry',
        customer: 'عبدالله القحطاني',
        customerEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedTo: 'فاطمة عبدالفتاح',
        assignedToEn: 'Fatima Abdelfattah',
        assignedBy: 'م. كريم وجدي',
        assignedByEn: 'Eng. Karim Wagdi',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-05',
        priority: 'High',
        createdDate: '2026-02-24',
    },
    {
        id: 'tb-18',
        ticketId: 'TCK-2026-018',
        subject: 'استرداد مبالغ سداد مقيم المعلقة',
        subjectEn: 'Pending Muqeem SADAD payment refund',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'سارة الشمري',
        customerEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedTo: 'عمر الدوسري',
        assignedToEn: 'Omar Al-Dossary',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-03-02',
        priority: 'Medium',
        createdDate: '2026-02-20',
    },
    {
        id: 'tb-19',
        ticketId: 'TCK-2026-019',
        subject: 'نقل خدمات وافد بموافقة المنشأة السابقة',
        subjectEn: 'Employee transfer with prior establishment approval',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'محمد العتيبي',
        customerEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-02-28',
        priority: 'High',
        createdDate: '2026-02-18',
    },
    {
        id: 'tb-20',
        ticketId: 'TCK-2026-020',
        subject: 'إصدار تصريح عمل لموظف تحت التدريب',
        subjectEn: 'Trainee work permit issuance',
        ticketType: 'طلب إداري',
        ticketTypeEn: 'Administrative Request',
        customer: 'خالد المطيري',
        customerEn: 'Khalid Al-Mutairi',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-02-25',
        priority: 'Low',
        createdDate: '2026-02-15',
    },
    {
        id: 'tb-21',
        ticketId: 'TCK-2026-021',
        subject: 'تحميل بيان الرواتب الشهري في مدد',
        subjectEn: 'Upload monthly salary statement to Mudad',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'فهد الدوسري',
        customerEn: 'Fahad Al-Dossary',
        company: 'مؤسسة الرياض للحلول التقنية',
        companyEn: 'Riyadh Tech Solutions',
        assignedTo: null,
        assignedToEn: null,
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'replied',
        status: 'closed',
        closedDate: '2026-02-20',
        priority: 'Medium',
        createdDate: '2026-02-10',
    },
    {
        id: 'tb-22',
        ticketId: 'TCK-2026-022',
        subject: 'اعتراض على مخالفة تأخير توثيق العقود',
        subjectEn: 'Objection against contract verification delay penalty',
        ticketType: 'استفسار امتثال',
        ticketTypeEn: 'Compliance Inquiry',
        customer: 'عبدالله القحطاني',
        customerEn: 'Abdullah Al-Qahtani',
        company: 'شركة الراجحي للصناعات',
        companyEn: 'Al Rajhi Industries',
        assignedTo: 'فاطمة عبدالفتاح',
        assignedToEn: 'Fatima Abdelfattah',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'waiting_customer',
        status: 'reopened',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-02-08',
    },
    {
        id: 'tb-23',
        ticketId: 'TCK-2026-023',
        subject: 'طلب ترقية الباقة الشهرية للبوابة الرقمية',
        subjectEn: 'Digital portal monthly subscription upgrade',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'سارة الشمري',
        customerEn: 'Sarah Al-Shammari',
        company: 'مجموعة الفوزان القابضة',
        companyEn: 'Al Fozan Holding',
        assignedTo: 'م. كريم وجدي',
        assignedToEn: 'Eng. Karim Wagdi',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'replied',
        status: 'open',
        closedDate: null,
        priority: 'Medium',
        createdDate: '2026-02-05',
    },
    {
        id: 'tb-24',
        ticketId: 'TCK-2026-024',
        subject: 'تسجيل الدخول الموحد عبر النفاذ الوطني',
        subjectEn: 'SSO configuration via National Nafath',
        ticketType: 'الدعم الفني',
        ticketTypeEn: 'Technical Support',
        customer: 'محمد العتيبي',
        customerEn: 'Mohammed Al-Otaibi',
        company: 'شركة المراعي للتجارة',
        companyEn: 'Almarai Trading',
        assignedTo: 'أحمد السالم',
        assignedToEn: 'Ahmed Al-Salem',
        assignedBy: 'التوجيه الآلي للمنظومة',
        assignedByEn: 'System Auto-Dispatch',
        replyStatus: 'pending_agent',
        status: 'open',
        closedDate: null,
        priority: 'High',
        createdDate: '2026-02-02',
    },
    {
        id: 'tb-25',
        ticketId: 'TCK-2026-025',
        subject: 'فحص توافق أرقام الآيبان للتحويلات الحكومية',
        subjectEn: 'IBAN compatibility check for gov payments',
        ticketType: 'الفواتير والمدفوعات',
        ticketTypeEn: 'Billing & Payments',
        customer: 'فهد الدوسري',
        customerEn: 'Fahad Al-Dossary',
        company: 'شركة دار الأركان للتطوير',
        companyEn: 'Dar Al Arkan Dev',
        assignedTo: 'عمر الدوسري',
        assignedToEn: 'Omar Al-Dossary',
        assignedBy: 'مشرف العمليات',
        assignedByEn: 'Operations Supervisor',
        replyStatus: 'waiting_customer',
        status: 'reopened',
        closedDate: null,
        priority: 'Low',
        createdDate: '2026-01-29',
    },
];

