export type EdmsCategoryKey = 'establishments' | 'employees' | 'assets';

export type EdmsDocumentTypeKey =
    | 'employee_health_insurance'
    | 'employee_contract'
    | 'passport'
    | 'iqama'
    | 'commercial_registration'
    | 'baladi_license'
    | 'gosi_subscription'
    | 'business_health_insurance';

export type EdmsDocumentScope = 'employee' | 'business';

export interface EdmsFilterOption {
    id: string;
    labelEn: string;
    labelAr: string;
    companyId?: string;
    companyEn?: string;
    companyAr?: string;
}

export interface EdmsDemoDocument {
    id: string;
    code: string;
    titleEn: string;
    titleAr: string;
    documentForEn: string;
    documentForAr: string;
    categoryKey: EdmsCategoryKey;
    categoryAr: 'منشأت' | 'موظفيين' | 'اصول';
    categoryEn: string;
    typeKey: EdmsDocumentTypeKey;
    typeEn:
        | 'Employee Health Insurance'
        | 'Employee Contract'
        | 'Passport'
        | 'Iqama'
        | 'Commercial Registration'
        | 'Baladi License'
        | 'GOSI Subscription'
        | 'Business Health Insurance';
    typeAr: string;
    companyId: string;
    companyEn: string;
    companyAr: string;
    employeeId?: string;
    employeeNameEn?: string;
    employeeNameAr?: string;
    holderNameEn: string;
    holderNameAr: string;
    createdByEn: string;
    createdByAr: string;
    createdByEmail: string;
    status: 'Active';
    scope: EdmsDocumentScope;
    issueDate: string;
    expiryDate: string;
    daysUntilExpiry: number;
    isExpiringSoon: boolean;
}

export const EDMS_CATEGORY_META: Record<
    EdmsCategoryKey,
    { key: EdmsCategoryKey; ar: 'منشأت' | 'موظفيين' | 'اصول'; en: string; color: string }
> = {
    employees: {
        key: 'employees',
        ar: 'موظفيين',
        en: 'موظفيين',
        color: '#2D3F2C',
    },
    establishments: {
        key: 'establishments',
        ar: 'منشأت',
        en: 'منشأت',
        color: '#6A7358',
    },
    assets: {
        key: 'assets',
        ar: 'اصول',
        en: 'اصول',
        color: '#BFAB93',
    },
};

export const EDMS_DOCUMENT_TYPE_META: Record<
    EdmsDocumentTypeKey,
    {
        key: EdmsDocumentTypeKey;
        en: EdmsDemoDocument['typeEn'];
        ar: string;
        scope: EdmsDocumentScope;
        defaultCategory: EdmsCategoryKey;
    }
> = {
    iqama: {
        key: 'iqama',
        en: 'Iqama',
        ar: 'الإقامة (هوية مقيم)',
        scope: 'employee',
        defaultCategory: 'employees',
    },
    employee_contract: {
        key: 'employee_contract',
        en: 'Employee Contract',
        ar: 'عقد العمل',
        scope: 'employee',
        defaultCategory: 'employees',
    },
    employee_health_insurance: {
        key: 'employee_health_insurance',
        en: 'Employee Health Insurance',
        ar: 'التأمين الطبي للموظفين',
        scope: 'employee',
        defaultCategory: 'employees',
    },
    passport: {
        key: 'passport',
        en: 'Passport',
        ar: 'جواز السفر',
        scope: 'employee',
        defaultCategory: 'employees',
    },
    commercial_registration: {
        key: 'commercial_registration',
        en: 'Commercial Registration',
        ar: 'السجل التجاري',
        scope: 'business',
        defaultCategory: 'establishments',
    },
    baladi_license: {
        key: 'baladi_license',
        en: 'Baladi License',
        ar: 'رخصة بلدي',
        scope: 'business',
        defaultCategory: 'assets',
    },
    gosi_subscription: {
        key: 'gosi_subscription',
        en: 'GOSI Subscription',
        ar: 'شهادة التأمينات الاجتماعية (GOSI)',
        scope: 'business',
        defaultCategory: 'establishments',
    },
    business_health_insurance: {
        key: 'business_health_insurance',
        en: 'Business Health Insurance',
        ar: 'التأمين الطبي للمنشأة',
        scope: 'business',
        defaultCategory: 'establishments',
    },
};

export const EDMS_COMPANY_OPTIONS: EdmsFilterOption[] = [
    {
        id: 'COMP-01',
        labelEn: 'AWN Administrative Services',
        labelAr: 'شركة عون للخدمات الإدارية',
    },
    {
        id: 'COMP-02',
        labelEn: 'Al Faisaliah Holding Group',
        labelAr: 'مجموعة الفيصلية القابضة',
    },
    {
        id: 'COMP-03',
        labelEn: 'Najd Integrated Solutions',
        labelAr: 'شركة نجد للحلول المتكاملة',
    },
    {
        id: 'COMP-04',
        labelEn: 'Gulf Industrial Supplies',
        labelAr: 'شركة الخليج للتوريدات الصناعية',
    },
    {
        id: 'COMP-05',
        labelEn: 'Al Yamamah Contracting Est.',
        labelAr: 'مؤسسة اليمامة للمقاولات',
    },
    {
        id: 'COMP-06',
        labelEn: 'Tuwaiq Logistics Co.',
        labelAr: 'شركة طويق للخدمات اللوجستية',
    },
];

export const EDMS_EMPLOYEE_OPTIONS: EdmsFilterOption[] = [
    {
        id: 'EMP-01',
        labelEn: 'Tariq Al-Mansoor',
        labelAr: 'طارق المنصور',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
    },
    {
        id: 'EMP-02',
        labelEn: 'Fahad Al-Otaibi',
        labelAr: 'فهد العتيبي',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
    },
    {
        id: 'EMP-03',
        labelEn: 'Reem Al-Qahtani',
        labelAr: 'ريم القحطاني',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
    },
    {
        id: 'EMP-04',
        labelEn: 'Kareem El-Sayed',
        labelAr: 'كريم السيد',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
    },
    {
        id: 'EMP-05',
        labelEn: 'Salman Al-Dossary',
        labelAr: 'سلمان الدوسري',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
    },
    {
        id: 'EMP-06',
        labelEn: 'Bilal Khan',
        labelAr: 'بلال خان',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
    },
    {
        id: 'EMP-07',
        labelEn: 'Maha Al-Zahrani',
        labelAr: 'مها الزهراني',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
    },
    {
        id: 'EMP-08',
        labelEn: 'Omar Al-Farooq',
        labelAr: 'عمر الفاروق',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
    },
    {
        id: 'EMP-09',
        labelEn: 'Abdullah Al-Harbi',
        labelAr: 'عبدالله الحربي',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
    },
    {
        id: 'EMP-10',
        labelEn: 'Mahmoud Hassan',
        labelAr: 'محمود حسن',
        companyId: 'COMP-05',
        companyEn: 'Al Yamamah Contracting Est.',
        companyAr: 'مؤسسة اليمامة للمقاولات',
    },
    {
        id: 'EMP-11',
        labelEn: 'Naveed Ahmed',
        labelAr: 'نفيد أحمد',
        companyId: 'COMP-06',
        companyEn: 'Tuwaiq Logistics Co.',
        companyAr: 'شركة طويق للخدمات اللوجستية',
    },
];

// 28 Coherent EDMS Documents (DOC060 down to DOC033) shared between Dashboard & Documents page
export const EDMS_DEMO_DOCUMENTS: EdmsDemoDocument[] = [
    {
        id: 'DOC060',
        code: 'DOC060',
        titleEn: 'Main Commercial Registration - Riyadh HQ',
        titleAr: 'السجل التجاري الرئيسي - المقر الرئيسي بالرياض',
        documentForEn: 'AWN Administrative Services',
        documentForAr: 'شركة عون للخدمات الإدارية',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'commercial_registration',
        typeEn: 'Commercial Registration',
        typeAr: 'السجل التجاري',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        holderNameEn: 'AWN Riyadh Headquarters',
        holderNameAr: 'المقر الرئيسي - الرياض',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-04-12',
        expiryDate: '2026-04-12',
        daysUntilExpiry: 7,
        isExpiringSoon: true,
    },
    {
        id: 'DOC059',
        code: 'DOC059',
        titleEn: 'Resident Identity (Iqama) - Tariq Al-Mansoor',
        titleAr: 'هوية مقيم (إقامة) - طارق المنصور',
        documentForEn: 'Tariq Al-Mansoor (AWN Administrative Services)',
        documentForAr: 'طارق المنصور (شركة عون للخدمات الإدارية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'iqama',
        typeEn: 'Iqama',
        typeAr: 'الإقامة (هوية مقيم)',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        employeeId: 'EMP-01',
        employeeNameEn: 'Tariq Al-Mansoor',
        employeeNameAr: 'طارق المنصور',
        holderNameEn: 'Tariq Al-Mansoor',
        holderNameAr: 'طارق المنصور',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-04-19',
        expiryDate: '2026-04-19',
        daysUntilExpiry: 14,
        isExpiringSoon: true,
    },
    {
        id: 'DOC058',
        code: 'DOC058',
        titleEn: 'GOSI Compliance Certificate - Q2 2026',
        titleAr: 'شهادة الالتزام بالتأمينات الاجتماعية - الربع الثاني 2026',
        documentForEn: 'AWN Administrative Services',
        documentForAr: 'شركة عون للخدمات الإدارية',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'gosi_subscription',
        typeEn: 'GOSI Subscription',
        typeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        holderNameEn: 'AWN Administrative Services',
        holderNameAr: 'شركة عون للخدمات الإدارية',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-07-01',
        expiryDate: '2026-07-01',
        daysUntilExpiry: 87,
        isExpiringSoon: false,
    },
    {
        id: 'DOC057',
        code: 'DOC057',
        titleEn: 'Resident Identity (Iqama) - Omar Al-Farooq',
        titleAr: 'هوية مقيم (إقامة) - عمر الفاروق',
        documentForEn: 'Omar Al-Farooq (Gulf Industrial Supplies)',
        documentForAr: 'عمر الفاروق (شركة الخليج للتوريدات الصناعية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'iqama',
        typeEn: 'Iqama',
        typeAr: 'الإقامة (هوية مقيم)',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
        employeeId: 'EMP-08',
        employeeNameEn: 'Omar Al-Farooq',
        employeeNameAr: 'عمر الفاروق',
        holderNameEn: 'Omar Al-Farooq',
        holderNameAr: 'عمر الفاروق',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-04-15',
        expiryDate: '2026-04-15',
        daysUntilExpiry: 10,
        isExpiringSoon: true,
    },
    {
        id: 'DOC056',
        code: 'DOC056',
        titleEn: 'Municipal Facility Permit - Olaya Tower Asset',
        titleAr: 'رخصة بلدي للمقر التشغيلي - برج العليا',
        documentForEn: 'AWN Administrative Services',
        documentForAr: 'شركة عون للخدمات الإدارية',
        categoryKey: 'assets',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
        typeKey: 'baladi_license',
        typeEn: 'Baladi License',
        typeAr: 'رخصة بلدي',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        holderNameEn: 'Olaya Operations Hub',
        holderNameAr: 'المقر التشغيلي - برج العليا',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-08-10',
        expiryDate: '2026-08-10',
        daysUntilExpiry: 127,
        isExpiringSoon: false,
    },
    {
        id: 'DOC055',
        code: 'DOC055',
        titleEn: 'Qiwa Authenticated Contract - Fahad Al-Otaibi',
        titleAr: 'عقد عمل موثق (قوى) - فهد العتيبي',
        documentForEn: 'Fahad Al-Otaibi (AWN Administrative Services)',
        documentForAr: 'فهد العتيبي (شركة عون للخدمات الإدارية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_contract',
        typeEn: 'Employee Contract',
        typeAr: 'عقد العمل',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        employeeId: 'EMP-02',
        employeeNameEn: 'Fahad Al-Otaibi',
        employeeNameAr: 'فهد العتيبي',
        holderNameEn: 'Fahad Al-Otaibi',
        holderNameAr: 'فهد العتيبي',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-06-01',
        expiryDate: '2026-06-01',
        daysUntilExpiry: 57,
        isExpiringSoon: false,
    },
    {
        id: 'DOC054',
        code: 'DOC054',
        titleEn: 'Baladi Commercial Complex License - King Fahd Rd',
        titleAr: 'رخصة بلدي للمجمع التجاري - طريق الملك فهد',
        documentForEn: 'Al Faisaliah Holding Group',
        documentForAr: 'مجموعة الفيصلية القابضة',
        categoryKey: 'assets',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
        typeKey: 'baladi_license',
        typeEn: 'Baladi License',
        typeAr: 'رخصة بلدي',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        holderNameEn: 'King Fahd Commercial Asset',
        holderNameAr: 'أصل المجمع التجاري - طريق الملك فهد',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-04-23',
        expiryDate: '2026-04-23',
        daysUntilExpiry: 18,
        isExpiringSoon: true,
    },
    {
        id: 'DOC053',
        code: 'DOC053',
        titleEn: 'CCHI Medical Coverage Card - Reem Al-Qahtani',
        titleAr: 'بطاقة التأمين الطبي للموظف - ريم القحطاني',
        documentForEn: 'Reem Al-Qahtani (AWN Administrative Services)',
        documentForAr: 'ريم القحطاني (شركة عون للخدمات الإدارية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_health_insurance',
        typeEn: 'Employee Health Insurance',
        typeAr: 'التأمين الطبي للموظفين',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        employeeId: 'EMP-03',
        employeeNameEn: 'Reem Al-Qahtani',
        employeeNameAr: 'ريم القحطاني',
        holderNameEn: 'Reem Al-Qahtani',
        holderNameAr: 'ريم القحطاني',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-09-15',
        expiryDate: '2026-09-15',
        daysUntilExpiry: 163,
        isExpiringSoon: false,
    },
    {
        id: 'DOC052',
        code: 'DOC052',
        titleEn: 'Commercial Registration - Al Faisaliah Holding',
        titleAr: 'السجل التجاري - مجموعة الفيصلية القابضة',
        documentForEn: 'Al Faisaliah Holding Group',
        documentForAr: 'مجموعة الفيصلية القابضة',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'commercial_registration',
        typeEn: 'Commercial Registration',
        typeAr: 'السجل التجاري',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        holderNameEn: 'Al Faisaliah Central CR',
        holderNameAr: 'السجل الرئيسي - الفيصلية',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-07-20',
        expiryDate: '2026-07-20',
        daysUntilExpiry: 106,
        isExpiringSoon: false,
    },
    {
        id: 'DOC051',
        code: 'DOC051',
        titleEn: 'Travel Passport Copy - Tariq Al-Mansoor',
        titleAr: 'نسخة جواز السفر - طارق المنصور',
        documentForEn: 'Tariq Al-Mansoor (AWN Administrative Services)',
        documentForAr: 'طارق المنصور (شركة عون للخدمات الإدارية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'passport',
        typeEn: 'Passport',
        typeAr: 'جواز السفر',
        companyId: 'COMP-01',
        companyEn: 'AWN Administrative Services',
        companyAr: 'شركة عون للخدمات الإدارية',
        employeeId: 'EMP-01',
        employeeNameEn: 'Tariq Al-Mansoor',
        employeeNameAr: 'طارق المنصور',
        holderNameEn: 'Tariq Al-Mansoor',
        holderNameAr: 'طارق المنصور',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2024-11-20',
        expiryDate: '2026-11-20',
        daysUntilExpiry: 229,
        isExpiringSoon: false,
    },
    {
        id: 'DOC050',
        code: 'DOC050',
        titleEn: 'GOSI Subscription Certificate - Al Faisaliah',
        titleAr: 'شهادة اشتراك التأمينات الاجتماعية - الفيصلية',
        documentForEn: 'Al Faisaliah Holding Group',
        documentForAr: 'مجموعة الفيصلية القابضة',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'gosi_subscription',
        typeEn: 'GOSI Subscription',
        typeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        holderNameEn: 'Al Faisaliah Holding Group',
        holderNameAr: 'مجموعة الفيصلية القابضة',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-05-01',
        expiryDate: '2026-05-01',
        daysUntilExpiry: 26,
        isExpiringSoon: true,
    },
    {
        id: 'DOC049',
        code: 'DOC049',
        titleEn: 'Resident Identity (Iqama) - Kareem El-Sayed',
        titleAr: 'هوية مقيم (إقامة) - كريم السيد',
        documentForEn: 'Kareem El-Sayed (Al Faisaliah Holding Group)',
        documentForAr: 'كريم السيد (مجموعة الفيصلية القابضة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'iqama',
        typeEn: 'Iqama',
        typeAr: 'الإقامة (هوية مقيم)',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        employeeId: 'EMP-04',
        employeeNameEn: 'Kareem El-Sayed',
        employeeNameAr: 'كريم السيد',
        holderNameEn: 'Kareem El-Sayed',
        holderNameAr: 'كريم السيد',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-08-01',
        expiryDate: '2026-08-01',
        daysUntilExpiry: 118,
        isExpiringSoon: false,
    },
    {
        id: 'DOC048',
        code: 'DOC048',
        titleEn: 'Executive Employment Contract - Salman Al-Dossary',
        titleAr: 'عقد عمل تنفيذي - سلمان الدوسري',
        documentForEn: 'Salman Al-Dossary (Al Faisaliah Holding Group)',
        documentForAr: 'سلمان الدوسري (مجموعة الفيصلية القابضة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_contract',
        typeEn: 'Employee Contract',
        typeAr: 'عقد العمل',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        employeeId: 'EMP-05',
        employeeNameEn: 'Salman Al-Dossary',
        employeeNameAr: 'سلمان الدوسري',
        holderNameEn: 'Salman Al-Dossary',
        holderNameAr: 'سلمان الدوسري',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-09-01',
        expiryDate: '2026-09-01',
        daysUntilExpiry: 149,
        isExpiringSoon: false,
    },
    {
        id: 'DOC047',
        code: 'DOC047',
        titleEn: 'Employee Health Insurance - Kareem El-Sayed',
        titleAr: 'التأمين الطبي للموظف - كريم السيد',
        documentForEn: 'Kareem El-Sayed (Al Faisaliah Holding Group)',
        documentForAr: 'كريم السيد (مجموعة الفيصلية القابضة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_health_insurance',
        typeEn: 'Employee Health Insurance',
        typeAr: 'التأمين الطبي للموظفين',
        companyId: 'COMP-02',
        companyEn: 'Al Faisaliah Holding Group',
        companyAr: 'مجموعة الفيصلية القابضة',
        employeeId: 'EMP-04',
        employeeNameEn: 'Kareem El-Sayed',
        employeeNameAr: 'كريم السيد',
        holderNameEn: 'Kareem El-Sayed',
        holderNameAr: 'كريم السيد',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-05-08',
        expiryDate: '2026-05-08',
        daysUntilExpiry: 33,
        isExpiringSoon: true,
    },
    {
        id: 'DOC046',
        code: 'DOC046',
        titleEn: 'Commercial Registration - Najd Digital Branch',
        titleAr: 'السجل التجاري - فرع نجد للحلول الرقمية',
        documentForEn: 'Najd Integrated Solutions',
        documentForAr: 'شركة نجد للحلول المتكاملة',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'commercial_registration',
        typeEn: 'Commercial Registration',
        typeAr: 'السجل التجاري',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        holderNameEn: 'Najd Integrated Solutions',
        holderNameAr: 'شركة نجد للحلول المتكاملة',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-06-15',
        expiryDate: '2026-06-15',
        daysUntilExpiry: 71,
        isExpiringSoon: false,
    },
    {
        id: 'DOC045',
        code: 'DOC045',
        titleEn: 'Baladi Technical Center License - Digital City Asset',
        titleAr: 'رخصة بلدي للمركز التقني - أصل المدينة الرقمية',
        documentForEn: 'Najd Integrated Solutions',
        documentForAr: 'شركة نجد للحلول المتكاملة',
        categoryKey: 'assets',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
        typeKey: 'baladi_license',
        typeEn: 'Baladi License',
        typeAr: 'رخصة بلدي',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        holderNameEn: 'Digital City Campus Asset',
        holderNameAr: 'مقر المدينة الرقمية - الرياض',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-07-10',
        expiryDate: '2026-07-10',
        daysUntilExpiry: 96,
        isExpiringSoon: false,
    },
    {
        id: 'DOC044',
        code: 'DOC044',
        titleEn: 'Resident Identity (Iqama) - Bilal Khan',
        titleAr: 'هوية مقيم (إقامة) - بلال خان',
        documentForEn: 'Bilal Khan (Najd Integrated Solutions)',
        documentForAr: 'بلال خان (شركة نجد للحلول المتكاملة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'iqama',
        typeEn: 'Iqama',
        typeAr: 'الإقامة (هوية مقيم)',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        employeeId: 'EMP-06',
        employeeNameEn: 'Bilal Khan',
        employeeNameAr: 'بلال خان',
        holderNameEn: 'Bilal Khan',
        holderNameAr: 'بلال خان',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-08-19',
        expiryDate: '2026-08-19',
        daysUntilExpiry: 136,
        isExpiringSoon: false,
    },
    {
        id: 'DOC043',
        code: 'DOC043',
        titleEn: 'Business Health Insurance Policy - Najd Staff',
        titleAr: 'وثيقة التأمين الطبي للمنشأة - شركة نجد',
        documentForEn: 'Najd Integrated Solutions',
        documentForAr: 'شركة نجد للحلول المتكاملة',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'business_health_insurance',
        typeEn: 'Business Health Insurance',
        typeAr: 'التأمين الطبي للمنشأة',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        holderNameEn: 'Najd Corporate Health Plan',
        holderNameAr: 'وثيقة نجد للتأمين الطبي',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-05-14',
        expiryDate: '2026-05-14',
        daysUntilExpiry: 39,
        isExpiringSoon: true,
    },
    {
        id: 'DOC042',
        code: 'DOC042',
        titleEn: 'Employment Contract - Maha Al-Zahrani',
        titleAr: 'عقد العمل الموحد - مها الزهراني',
        documentForEn: 'Maha Al-Zahrani (Najd Integrated Solutions)',
        documentForAr: 'مها الزهراني (شركة نجد للحلول المتكاملة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_contract',
        typeEn: 'Employee Contract',
        typeAr: 'عقد العمل',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        employeeId: 'EMP-07',
        employeeNameEn: 'Maha Al-Zahrani',
        employeeNameAr: 'مها الزهراني',
        holderNameEn: 'Maha Al-Zahrani',
        holderNameAr: 'مها الزهراني',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-10-12',
        expiryDate: '2026-10-12',
        daysUntilExpiry: 190,
        isExpiringSoon: false,
    },
    {
        id: 'DOC041',
        code: 'DOC041',
        titleEn: 'Industrial Commercial Registration - Dammam Plant',
        titleAr: 'السجل التجاري الصناعي - مصنع الدمام',
        documentForEn: 'Gulf Industrial Supplies',
        documentForAr: 'شركة الخليج للتوريدات الصناعية',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'commercial_registration',
        typeEn: 'Commercial Registration',
        typeAr: 'السجل التجاري',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
        holderNameEn: 'Gulf Industrial Dammam',
        holderNameAr: 'فرع المدينة الصناعية الثانية - الدمام',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-09-01',
        expiryDate: '2026-09-01',
        daysUntilExpiry: 149,
        isExpiringSoon: false,
    },
    {
        id: 'DOC040',
        code: 'DOC040',
        titleEn: 'Baladi Warehouse Operating License - Asset #W-14',
        titleAr: 'رخصة بلدي لتشغيل المستودع المركزي - أصل #W-14',
        documentForEn: 'Gulf Industrial Supplies',
        documentForAr: 'شركة الخليج للتوريدات الصناعية',
        categoryKey: 'assets',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
        typeKey: 'baladi_license',
        typeEn: 'Baladi License',
        typeAr: 'رخصة بلدي',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
        holderNameEn: 'Central Warehouse Asset #W-14',
        holderNameAr: 'المستودع المركزي - أصل #W-14',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-08-25',
        expiryDate: '2026-08-25',
        daysUntilExpiry: 142,
        isExpiringSoon: false,
    },
    {
        id: 'DOC039',
        code: 'DOC039',
        titleEn: 'Passport Document - Bilal Khan',
        titleAr: 'جواز السفر - بلال خان',
        documentForEn: 'Bilal Khan (Najd Integrated Solutions)',
        documentForAr: 'بلال خان (شركة نجد للحلول المتكاملة)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'passport',
        typeEn: 'Passport',
        typeAr: 'جواز السفر',
        companyId: 'COMP-03',
        companyEn: 'Najd Integrated Solutions',
        companyAr: 'شركة نجد للحلول المتكاملة',
        employeeId: 'EMP-06',
        employeeNameEn: 'Bilal Khan',
        employeeNameAr: 'بلال خان',
        holderNameEn: 'Bilal Khan',
        holderNameAr: 'بلال خان',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-05-20',
        expiryDate: '2026-05-20',
        daysUntilExpiry: 45,
        isExpiringSoon: true,
    },
    {
        id: 'DOC038',
        code: 'DOC038',
        titleEn: 'Employee Contract - Abdullah Al-Harbi',
        titleAr: 'عقد العمل - عبدالله الحربي',
        documentForEn: 'Abdullah Al-Harbi (Gulf Industrial Supplies)',
        documentForAr: 'عبدالله الحربي (شركة الخليج للتوريدات الصناعية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_contract',
        typeEn: 'Employee Contract',
        typeAr: 'عقد العمل',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
        employeeId: 'EMP-09',
        employeeNameEn: 'Abdullah Al-Harbi',
        employeeNameAr: 'عبدالله الحربي',
        holderNameEn: 'Abdullah Al-Harbi',
        holderNameAr: 'عبدالله الحربي',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-11-01',
        expiryDate: '2026-11-01',
        daysUntilExpiry: 210,
        isExpiringSoon: false,
    },
    {
        id: 'DOC037',
        code: 'DOC037',
        titleEn: 'Employee Health Insurance - Omar Al-Farooq',
        titleAr: 'التأمين الطبي للموظف - عمر الفاروق',
        documentForEn: 'Omar Al-Farooq (Gulf Industrial Supplies)',
        documentForAr: 'عمر الفاروق (شركة الخليج للتوريدات الصناعية)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'employee_health_insurance',
        typeEn: 'Employee Health Insurance',
        typeAr: 'التأمين الطبي للموظفين',
        companyId: 'COMP-04',
        companyEn: 'Gulf Industrial Supplies',
        companyAr: 'شركة الخليج للتوريدات الصناعية',
        employeeId: 'EMP-08',
        employeeNameEn: 'Omar Al-Farooq',
        employeeNameAr: 'عمر الفاروق',
        holderNameEn: 'Omar Al-Farooq',
        holderNameAr: 'عمر الفاروق',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-08-12',
        expiryDate: '2026-08-12',
        daysUntilExpiry: 129,
        isExpiringSoon: false,
    },
    {
        id: 'DOC036',
        code: 'DOC036',
        titleEn: 'Commercial Registration - Al Yamamah Contracting',
        titleAr: 'السجل التجاري - مؤسسة اليمامة للمقاولات',
        documentForEn: 'Al Yamamah Contracting Est.',
        documentForAr: 'مؤسسة اليمامة للمقاولات',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'commercial_registration',
        typeEn: 'Commercial Registration',
        typeAr: 'السجل التجاري',
        companyId: 'COMP-05',
        companyEn: 'Al Yamamah Contracting Est.',
        companyAr: 'مؤسسة اليمامة للمقاولات',
        holderNameEn: 'Al Yamamah Contracting Est.',
        holderNameAr: 'مؤسسة اليمامة للمقاولات',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-07-18',
        expiryDate: '2026-07-18',
        daysUntilExpiry: 104,
        isExpiringSoon: false,
    },
    {
        id: 'DOC035',
        code: 'DOC035',
        titleEn: 'Resident Identity (Iqama) - Mahmoud Hassan',
        titleAr: 'هوية مقيم (إقامة) - محمود حسن',
        documentForEn: 'Mahmoud Hassan (Al Yamamah Contracting Est.)',
        documentForAr: 'محمود حسن (مؤسسة اليمامة للمقاولات)',
        categoryKey: 'employees',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
        typeKey: 'iqama',
        typeEn: 'Iqama',
        typeAr: 'الإقامة (هوية مقيم)',
        companyId: 'COMP-05',
        companyEn: 'Al Yamamah Contracting Est.',
        companyAr: 'مؤسسة اليمامة للمقاولات',
        employeeId: 'EMP-10',
        employeeNameEn: 'Mahmoud Hassan',
        employeeNameAr: 'محمود حسن',
        holderNameEn: 'Mahmoud Hassan',
        holderNameAr: 'محمود حسن',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
        scope: 'employee',
        issueDate: '2025-04-28',
        expiryDate: '2026-04-28',
        daysUntilExpiry: 23,
        isExpiringSoon: true,
    },
    {
        id: 'DOC034',
        code: 'DOC034',
        titleEn: 'GOSI Certificate - Al Yamamah Contracting',
        titleAr: 'شهادة التأمينات الاجتماعية - مؤسسة اليمامة',
        documentForEn: 'Al Yamamah Contracting Est.',
        documentForAr: 'مؤسسة اليمامة للمقاولات',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'gosi_subscription',
        typeEn: 'GOSI Subscription',
        typeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        companyId: 'COMP-05',
        companyEn: 'Al Yamamah Contracting Est.',
        companyAr: 'مؤسسة اليمامة للمقاولات',
        holderNameEn: 'Al Yamamah Contracting Est.',
        holderNameAr: 'مؤسسة اليمامة للمقاولات',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-08-01',
        expiryDate: '2026-08-01',
        daysUntilExpiry: 118,
        isExpiringSoon: false,
    },
    {
        id: 'DOC033',
        code: 'DOC033',
        titleEn: 'Corporate Health Insurance - Tuwaiq Logistics',
        titleAr: 'وثيقة التأمين الطبي للمنشأة - طويق اللوجستية',
        documentForEn: 'Tuwaiq Logistics Co.',
        documentForAr: 'شركة طويق للخدمات اللوجستية',
        categoryKey: 'establishments',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
        typeKey: 'business_health_insurance',
        typeEn: 'Business Health Insurance',
        typeAr: 'التأمين الطبي للمنشأة',
        companyId: 'COMP-06',
        companyEn: 'Tuwaiq Logistics Co.',
        companyAr: 'شركة طويق للخدمات اللوجستية',
        holderNameEn: 'Tuwaiq Logistics Co.',
        holderNameAr: 'شركة طويق للخدمات اللوجستية',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
        scope: 'business',
        issueDate: '2025-09-20',
        expiryDate: '2026-09-20',
        daysUntilExpiry: 168,
        isExpiringSoon: false,
    },
];

// ============================================================================
// EDMS Document Templates Master Dataset (23 Templates)
// ============================================================================

export type EdmsTemplateTag = 'CR Registration' | 'Muqeem' | 'Mudad' | 'Absher' | 'GOSI';

export interface EdmsTemplateTagOption {
    value: EdmsTemplateTag;
    labelEn: string;
    labelAr: string;
}

export const EDMS_TEMPLATE_TAG_OPTIONS: EdmsTemplateTagOption[] = [
    { value: 'CR Registration', labelEn: 'CR Registration', labelAr: 'CR Registration (السجل التجاري)' },
    { value: 'Muqeem', labelEn: 'Muqeem', labelAr: 'Muqeem (مقيم)' },
    { value: 'Mudad', labelEn: 'Mudad', labelAr: 'Mudad (مدد)' },
    { value: 'Absher', labelEn: 'Absher', labelAr: 'Absher (أبشر)' },
    { value: 'GOSI', labelEn: 'GOSI', labelAr: 'GOSI (التأمينات الاجتماعية)' },
];

export interface EdmsTemplateDocTypeOption {
    value: string;
    labelEn: string;
    labelAr: string;
    categoryAr: string;
    categoryEn: string;
}

export const EDMS_TEMPLATE_DOC_TYPE_OPTIONS: EdmsTemplateDocTypeOption[] = [
    {
        value: 'Employee Health Insurance',
        labelEn: 'Employee Health Insurance',
        labelAr: 'التأمين الطبي للموظفين (Employee Health Insurance)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Employee Contract',
        labelEn: 'Employee Contract',
        labelAr: 'عقد العمل (Employee Contract)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Passport',
        labelEn: 'Passport',
        labelAr: 'جواز السفر (Passport)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Iqama',
        labelEn: 'Iqama',
        labelAr: 'الإقامة (Iqama)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Commercial Registration',
        labelEn: 'Commercial Registration',
        labelAr: 'السجل التجاري (Commercial Registration)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
    {
        value: 'Baladi License',
        labelEn: 'Baladi License',
        labelAr: 'رخصة بلدي (Baladi License)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
    {
        value: 'GOSI Subscription',
        labelEn: 'GOSI Subscription',
        labelAr: 'اشتراك التأمينات الاجتماعية (GOSI Subscription)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
    {
        value: 'Business Health Insurance',
        labelEn: 'Business Health Insurance',
        labelAr: 'التأمين الطبي للمنشأة (Business Health Insurance)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
    {
        value: 'Vehicle Registration',
        labelEn: 'Vehicle Registration',
        labelAr: 'رخصة سير المركبة - استمارة (Vehicle Registration)',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
    },
    {
        value: 'Vehicle Operation Card',
        labelEn: 'Vehicle Operation Card',
        labelAr: 'بطاقة تشغيل مركبة (Vehicle Operation Card)',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
    },
    {
        value: 'Vehicle Insurance',
        labelEn: 'Vehicle Insurance',
        labelAr: 'تأمين المركبة (Vehicle Insurance)',
        categoryAr: 'اصول',
        categoryEn: 'اصول',
    },
    {
        value: 'National Address',
        labelEn: 'National Address',
        labelAr: 'العنوان الوطني (National Address)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
    {
        value: 'Re entry Visa',
        labelEn: 'Re entry Visa',
        labelAr: 'تأشيرة خروج وعودة (Re entry Visa)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Final Exit Visa',
        labelEn: 'Final Exit Visa',
        labelAr: 'تأشيرة خروج نهائي (Final Exit Visa)',
        categoryAr: 'موظفيين',
        categoryEn: 'موظفيين',
    },
    {
        value: 'Qiwa Subscription',
        labelEn: 'Qiwa Subscription',
        labelAr: 'اشتراك منصة قوى (Qiwa Subscription)',
        categoryAr: 'منشأت',
        categoryEn: 'منشأت',
    },
];

export type EdmsTemplateBuilderElementType =
    | 'Text Field'
    | 'Text Area'
    | 'Checkbox'
    | 'Date Field'
    | 'Expiry Date'
    | 'File Upload'
    | 'Checkbox Group'
    | 'Number'
    | 'Header'
    | 'Paragraph'
    | 'Email'
    | 'Select';

export interface EdmsTemplateBuilderElement {
    id: string;
    type: EdmsTemplateBuilderElementType;
    label: string;
    options?: string[];
}

export interface EdmsDocumentTemplate {
    id: string;
    templateCode: string;
    templateName: string;
    templateNameAr: string;
    createDate: string;
    documentTag: string;
    documentCategory: string;
    documentType: string;
    documentTypeAr: string;
    createdByEn: string;
    createdByAr: string;
    createdByEmail: string;
    status: 'Active';
    elements?: EdmsTemplateBuilderElement[];
}

export const EDMS_DEMO_TEMPLATES: EdmsDocumentTemplate[] = [
    {
        id: 'tpl-1',
        templateCode: 'DTP054',
        templateName: 'طباعة شهاداة',
        templateNameAr: 'طباعة شهاداة',
        createDate: '2026-03-28',
        documentTag: 'GOSI',
        documentCategory: 'منشأت',
        documentType: 'GOSI Subscription',
        documentTypeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-2',
        templateCode: 'DTP023',
        templateName: 'Employee Health Insurance',
        templateNameAr: 'التأمين الطبي للموظفين',
        createDate: '2026-03-25',
        documentTag: 'Absher',
        documentCategory: 'موظفيين',
        documentType: 'Employee Health Insurance',
        documentTypeAr: 'التأمين الطبي للموظفين',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-3',
        templateCode: 'DTP022',
        templateName: 'Vehicle Registration',
        templateNameAr: 'رخصة سير المركبة (استمارة)',
        createDate: '2026-03-22',
        documentTag: 'Absher',
        documentCategory: 'اصول',
        documentType: 'Vehicle Registration',
        documentTypeAr: 'رخصة سير المركبة (استمارة)',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-4',
        templateCode: 'DTP021',
        templateName: 'Vehicle Operation Card',
        templateNameAr: 'بطاقة تشغيل مركبة',
        createDate: '2026-03-20',
        documentTag: 'Absher',
        documentCategory: 'اصول',
        documentType: 'Vehicle Operation Card',
        documentTypeAr: 'بطاقة تشغيل مركبة',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-5',
        templateCode: 'DTP020',
        templateName: 'Vehicle Insurance',
        templateNameAr: 'وثيقة تأمين المركبة',
        createDate: '2026-03-18',
        documentTag: 'Absher',
        documentCategory: 'اصول',
        documentType: 'Vehicle Insurance',
        documentTypeAr: 'تأمين المركبة',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-6',
        templateCode: 'DTP019',
        templateName: 'National Address',
        templateNameAr: 'شهادة العنوان الوطني للمنشأة',
        createDate: '2026-03-15',
        documentTag: 'CR Registration',
        documentCategory: 'منشأت',
        documentType: 'National Address',
        documentTypeAr: 'العنوان الوطني',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-7',
        templateCode: 'DTP018',
        templateName: 'Baladi License',
        templateNameAr: 'رخصة بلدي للأنشطة التجارية',
        createDate: '2026-03-12',
        documentTag: 'CR Registration',
        documentCategory: 'منشأت',
        documentType: 'Baladi License',
        documentTypeAr: 'رخصة بلدي',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-8',
        templateCode: 'DTP017',
        templateName: 'Re entry Visa',
        templateNameAr: 'تأشيرة خروج وعودة للموظف',
        createDate: '2026-03-10',
        documentTag: 'Muqeem',
        documentCategory: 'موظفيين',
        documentType: 'Re entry Visa',
        documentTypeAr: 'تأشيرة خروج وعودة',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-9',
        templateCode: 'DTP016',
        templateName: 'Final Exit Visa',
        templateNameAr: 'تأشيرة خروج نهائي',
        createDate: '2026-03-08',
        documentTag: 'Muqeem',
        documentCategory: 'موظفيين',
        documentType: 'Final Exit Visa',
        documentTypeAr: 'تأشيرة خروج نهائي',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-10',
        templateCode: 'DTP015',
        templateName: 'Qiwa Subscription',
        templateNameAr: 'شهادة اشتراك منصة قوى',
        createDate: '2026-03-05',
        documentTag: 'Mudad',
        documentCategory: 'منشأت',
        documentType: 'Qiwa Subscription',
        documentTypeAr: 'اشتراك منصة قوى',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-11',
        templateCode: 'DTP014',
        templateName: 'Commercial Registration',
        templateNameAr: 'السجل التجاري للمنشأة',
        createDate: '2026-03-02',
        documentTag: 'CR Registration',
        documentCategory: 'منشأت',
        documentType: 'Commercial Registration',
        documentTypeAr: 'السجل التجاري',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-12',
        templateCode: 'DTP013',
        templateName: 'Employee Contract',
        templateNameAr: 'عقد العمل الموحد للموظف',
        createDate: '2026-02-27',
        documentTag: 'Mudad',
        documentCategory: 'موظفيين',
        documentType: 'Employee Contract',
        documentTypeAr: 'عقد العمل',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-13',
        templateCode: 'DTP012',
        templateName: 'Iqama',
        templateNameAr: 'هوية مقيم (الإقامة)',
        createDate: '2026-02-24',
        documentTag: 'Muqeem',
        documentCategory: 'موظفيين',
        documentType: 'Iqama',
        documentTypeAr: 'الإقامة (هوية مقيم)',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-14',
        templateCode: 'DTP011',
        templateName: 'Passport',
        templateNameAr: 'وثيقة جواز السفر',
        createDate: '2026-02-20',
        documentTag: 'Muqeem',
        documentCategory: 'موظفيين',
        documentType: 'Passport',
        documentTypeAr: 'جواز السفر',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-15',
        templateCode: 'DTP010',
        templateName: 'GOSI Subscription',
        templateNameAr: 'شهادة اشتراك التأمينات الاجتماعية',
        createDate: '2026-02-18',
        documentTag: 'GOSI',
        documentCategory: 'منشأت',
        documentType: 'GOSI Subscription',
        documentTypeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-16',
        templateCode: 'DTP009',
        templateName: 'Business Health Insurance',
        templateNameAr: 'وثيقة التأمين الطبي للمنشأة',
        createDate: '2026-02-14',
        documentTag: 'CR Registration',
        documentCategory: 'منشأت',
        documentType: 'Business Health Insurance',
        documentTypeAr: 'التأمين الطبي للمنشأة',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-17',
        templateCode: 'DTP008',
        templateName: 'Mudad Wage Protection Certificate',
        templateNameAr: 'شهادة التزام حماية الأجور (مدد)',
        createDate: '2026-02-11',
        documentTag: 'Mudad',
        documentCategory: 'منشأت',
        documentType: 'GOSI Subscription',
        documentTypeAr: 'شهادة التأمينات الاجتماعية (GOSI)',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-18',
        templateCode: 'DTP007',
        templateName: 'Muqeem Resident Report Template',
        templateNameAr: 'قالب تقرير مقيم للموظف',
        createDate: '2026-02-08',
        documentTag: 'Muqeem',
        documentCategory: 'موظفيين',
        documentType: 'Iqama',
        documentTypeAr: 'الإقامة (هوية مقيم)',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-19',
        templateCode: 'DTP006',
        templateName: 'Branch Commercial Registration',
        templateNameAr: 'السجل التجاري الفرعي للمنشأة',
        createDate: '2026-02-04',
        documentTag: 'CR Registration',
        documentCategory: 'منشأت',
        documentType: 'Commercial Registration',
        documentTypeAr: 'السجل التجاري',
        createdByEn: 'Sultan Al-Harbi',
        createdByAr: 'سلطان الحربي',
        createdByEmail: 's.alharbi@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-20',
        templateCode: 'DTP005',
        templateName: 'Absher Fleet Authorization Permit',
        templateNameAr: 'تفويض قيادة مركبة عبر أبشر',
        createDate: '2026-01-29',
        documentTag: 'Absher',
        documentCategory: 'اصول',
        documentType: 'Vehicle Operation Card',
        documentTypeAr: 'بطاقة تشغيل مركبة',
        createdByEn: 'Fahad Al-Dosari',
        createdByAr: 'فهد الدوسري',
        createdByEmail: 'f.aldosari@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-21',
        templateCode: 'DTP004',
        templateName: 'Warehouse Baladi Operating Permit',
        templateNameAr: 'رخصة بلدي لتشغيل المستودعات',
        createDate: '2026-01-24',
        documentTag: 'CR Registration',
        documentCategory: 'اصول',
        documentType: 'Baladi License',
        documentTypeAr: 'رخصة بلدي',
        createdByEn: 'System Admin',
        createdByAr: 'مسؤول النظام',
        createdByEmail: 'admin@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-22',
        templateCode: 'DTP003',
        templateName: 'Executive Employment Agreement',
        templateNameAr: 'اتفاقية عقد العمل التنفيذي',
        createDate: '2026-01-19',
        documentTag: 'Mudad',
        documentCategory: 'موظفيين',
        documentType: 'Employee Contract',
        documentTypeAr: 'عقد العمل',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
    {
        id: 'tpl-23',
        templateCode: 'DTP002',
        templateName: 'Dependent Medical Insurance Card',
        templateNameAr: 'بطاقة التأمين الطبي للتابعين والموظفين',
        createDate: '2026-01-14',
        documentTag: 'Absher',
        documentCategory: 'موظفيين',
        documentType: 'Employee Health Insurance',
        documentTypeAr: 'التأمين الطبي للموظفين',
        createdByEn: 'Noura Al-Qahtani',
        createdByAr: 'نورة القحطاني',
        createdByEmail: 'n.alqahtani@awn.sa',
        status: 'Active',
    },
];

export function prependDemoTemplate(newItem: EdmsDocumentTemplate): void {
    EDMS_DEMO_TEMPLATES.unshift(newItem);
}

export function updateDemoTemplate(updatedItem: EdmsDocumentTemplate): void {
    const idx = EDMS_DEMO_TEMPLATES.findIndex((item) => item.id === updatedItem.id);
    if (idx !== -1) {
        EDMS_DEMO_TEMPLATES[idx] = updatedItem;
    }
}

export function removeDemoTemplate(id: string): void {
    const idx = EDMS_DEMO_TEMPLATES.findIndex((item) => item.id === id);
    if (idx !== -1) {
        EDMS_DEMO_TEMPLATES.splice(idx, 1);
    }
}

// ============================================================================
// EDMS Document Categories Master Dataset (Exact 3 Initial Categories)
// ============================================================================

export interface EdmsDocumentCategory {
    id: string;
    categoryCode: string;
    categoryName: string;
    description: string;
    createdByInitials: string;
    createdByEn: string;
    createdByAr: string;
    status: 'Active';
}

export const EDMS_DEMO_CATEGORIES: EdmsDocumentCategory[] = [
    {
        id: 'cat-3',
        categoryCode: 'DCG003',
        categoryName: 'اصول',
        description: 'اصول .',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'cat-2',
        categoryCode: 'DCG002',
        categoryName: 'موظفيين',
        description: 'موظفيين .',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'cat-1',
        categoryCode: 'DCG001',
        categoryName: 'منشأت',
        description: 'Business .',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
];

export function prependDemoCategory(newItem: EdmsDocumentCategory): void {
    EDMS_DEMO_CATEGORIES.unshift(newItem);
}

export function updateDemoCategory(updatedItem: EdmsDocumentCategory): void {
    const idx = EDMS_DEMO_CATEGORIES.findIndex((item) => item.id === updatedItem.id);
    if (idx !== -1) {
        EDMS_DEMO_CATEGORIES[idx] = updatedItem;
    }
}

export function removeDemoCategory(id: string): void {
    const idx = EDMS_DEMO_CATEGORIES.findIndex((item) => item.id === id);
    if (idx !== -1) {
        EDMS_DEMO_CATEGORIES.splice(idx, 1);
    }
}

export function getEdmsCategories(): EdmsDocumentCategory[] {
    return EDMS_DEMO_CATEGORIES;
}

// ============================================================================
// EDMS Document Types Master Dataset (34 Initial Document Types: DTY034 - DTY001)
// ============================================================================

export interface EdmsDocumentTypeRecord {
    id: string;
    typeCode: string;
    typeName: string;
    description: string;
    categoryId: string;
    categoryName: string;
    createdByInitials: string;
    createdByEn: string;
    createdByAr: string;
    status: 'Active';
}

export const EDMS_DEMO_DOCUMENT_TYPES: EdmsDocumentTypeRecord[] = [
    {
        id: 'dtype-34',
        typeCode: 'DTY034',
        typeName: 'طباعة شهادة',
        description: 'طباعة شهادة',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'EA',
        createdByEn: 'Emad Alhakami',
        createdByAr: 'عماد الحكمي',
        status: 'Active',
    },
    {
        id: 'dtype-33',
        typeCode: 'DTY033',
        typeName: 'شهادة',
        description: 'متعلق بجميع الشهاداة التي يتم تصديرها من المنصات الحكومية',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'EA',
        createdByEn: 'Emad Alhakami',
        createdByAr: 'عماد الحكمي',
        status: 'Active',
    },
    {
        id: 'dtype-32',
        typeCode: 'DTY032',
        typeName: 'Test Workflow Communication',
        description: 'Description',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'KA',
        createdByEn: 'Khalifah Alsharabi',
        createdByAr: 'خليفة الشرعبي',
        status: 'Active',
    },
    {
        id: 'dtype-31',
        typeCode: 'DTY031',
        typeName: 'تسجيل المركبات',
        description: 'تسجيل المركبات',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-30',
        typeCode: 'DTY030',
        typeName: 'كرت التشغيل المركبات',
        description: 'كرت التشغيل المركبات',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-29',
        typeCode: 'DTY029',
        typeName: 'تامين المركبات',
        description: 'تامين المركبات',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-28',
        typeCode: 'DTY028',
        typeName: 'اشتراك قوى للمنشات',
        description: 'اشتراك قوى للمنشات',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-27',
        typeCode: 'DTY027',
        typeName: 'اشتراك مدد للمنشات',
        description: 'اشتراك مدد للمنشات',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-26',
        typeCode: 'DTY026',
        typeName: 'اشتراك التامينات الاجتماعية للمنشات',
        description: 'اشتراك التامينات الاجتماعية للمنشات',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-25',
        typeCode: 'DTY025',
        typeName: 'اشتراك مقيم للمنشات',
        description: 'اشتراك مقيم للمنشات',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-24',
        typeCode: 'DTY024',
        typeName: 'Iqama',
        description: 'Resident identity card (Iqama) issued via Absher / Muqeem for company employees.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-23',
        typeCode: 'DTY023',
        typeName: 'Employee Contract',
        description: 'Unified Qiwa employment contract and job offer documentation.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-22',
        typeCode: 'DTY022',
        typeName: 'Employee Health Insurance',
        description: 'CCHI-compliant cooperative medical insurance policy for employees.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-21',
        typeCode: 'DTY021',
        typeName: 'Passport',
        description: 'Employee passport copy and travel document verification record.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-20',
        typeCode: 'DTY020',
        typeName: 'Commercial Registration',
        description: 'Ministry of Commerce commercial registration certificate (CR) for establishments.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-19',
        typeCode: 'DTY019',
        typeName: 'Baladi License',
        description: 'Municipal commercial and operational license issued via Baladi portal.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-18',
        typeCode: 'DTY018',
        typeName: 'GOSI Subscription',
        description: 'General Organization for Social Insurance (GOSI) compliance and subscription certificate.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-17',
        typeCode: 'DTY017',
        typeName: 'Business Health Insurance',
        description: 'Corporate group medical insurance policy for establishment compliance.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-16',
        typeCode: 'DTY016',
        typeName: 'Vehicle Registration',
        description: 'Vehicle registration license (Istimara) for fleet and corporate vehicles.',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-15',
        typeCode: 'DTY015',
        typeName: 'Vehicle Operation Card',
        description: 'Transport General Authority (TGA) operation card for commercial vehicles.',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-14',
        typeCode: 'DTY014',
        typeName: 'Vehicle Insurance',
        description: 'Motor comprehensive and third-party insurance policy for fleet assets.',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-13',
        typeCode: 'DTY013',
        typeName: 'National Address',
        description: 'SPL registered national address certificate for main office and branches.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-12',
        typeCode: 'DTY012',
        typeName: 'Re entry Visa',
        description: 'Exit and re-entry visa document issued through Muqeem / Absher Business.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-11',
        typeCode: 'DTY011',
        typeName: 'Final Exit Visa',
        description: 'Final exit visa and clearance certificate issued via Muqeem portal.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-10',
        typeCode: 'DTY010',
        typeName: 'Qiwa Subscription',
        description: 'Qiwa platform annual establishment subscription and localization certificate.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-9',
        typeCode: 'DTY009',
        typeName: 'ZATCA Tax Certificate',
        description: 'Zakat, Tax and Customs Authority (ZATCA) registration and compliance certificate.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'EA',
        createdByEn: 'Emad Alhakami',
        createdByAr: 'عماد الحكمي',
        status: 'Active',
    },
    {
        id: 'dtype-8',
        typeCode: 'DTY008',
        typeName: 'VAT Registration Certificate',
        description: 'Value Added Tax (VAT) registration certificate issued by ZATCA.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'EA',
        createdByEn: 'Emad Alhakami',
        createdByAr: 'عماد الحكمي',
        status: 'Active',
    },
    {
        id: 'dtype-7',
        typeCode: 'DTY007',
        typeName: 'Civil Defense License',
        description: 'Salamah civil defense safety and fire prevention license for facilities.',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'KA',
        createdByEn: 'Khalifah Alsharabi',
        createdByAr: 'خليفة الشرعبي',
        status: 'Active',
    },
    {
        id: 'dtype-6',
        typeCode: 'DTY006',
        typeName: 'Chamber of Commerce Certificate',
        description: 'Chamber of Commerce membership and attestation certificate.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'KA',
        createdByEn: 'Khalifah Alsharabi',
        createdByAr: 'خليفة الشرعبي',
        status: 'Active',
    },
    {
        id: 'dtype-5',
        typeCode: 'DTY005',
        typeName: 'Saudization Certificate (Nitaqat)',
        description: 'MHRSD Nitaqat compliance and Saudization certificate for establishments.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'EA',
        createdByEn: 'Emad Alhakami',
        createdByAr: 'عماد الحكمي',
        status: 'Active',
    },
    {
        id: 'dtype-4',
        typeCode: 'DTY004',
        typeName: 'Mudad Wage Protection Certificate',
        description: 'Mudad payroll compliance and Wage Protection System (WPS) certificate.',
        categoryId: 'cat-1',
        categoryName: 'منشأت',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-3',
        typeCode: 'DTY003',
        typeName: 'Professional Accreditation Certificate',
        description: 'Saudi Council of Engineers / SOCPA professional accreditation for employees.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-2',
        typeCode: 'DTY002',
        typeName: 'Medical Fitness Certificate',
        description: 'Baladi / MOH occupational health card and medical fitness report.',
        categoryId: 'cat-2',
        categoryName: 'موظفيين',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
    {
        id: 'dtype-1',
        typeCode: 'DTY001',
        typeName: 'Warehouse Lease Agreement',
        description: 'Ejar commercial property and warehouse lease contract for company assets.',
        categoryId: 'cat-3',
        categoryName: 'اصول',
        createdByInitials: 'UU',
        createdByEn: 'Unknown User',
        createdByAr: 'مستخدم غير معروف',
        status: 'Active',
    },
];

export function prependDemoDocumentType(newItem: EdmsDocumentTypeRecord): void {
    EDMS_DEMO_DOCUMENT_TYPES.unshift(newItem);
}

export function updateDemoDocumentType(updatedItem: EdmsDocumentTypeRecord): void {
    const idx = EDMS_DEMO_DOCUMENT_TYPES.findIndex((item) => item.id === updatedItem.id);
    if (idx !== -1) {
        EDMS_DEMO_DOCUMENT_TYPES[idx] = updatedItem;
    }
}

export function removeDemoDocumentType(id: string): void {
    const idx = EDMS_DEMO_DOCUMENT_TYPES.findIndex((item) => item.id === id);
    if (idx !== -1) {
        EDMS_DEMO_DOCUMENT_TYPES.splice(idx, 1);
    }
}

export function getEdmsTemplateDocTypeOptions(): EdmsTemplateDocTypeOption[] {
    const seen = new Set<string>();
    const result: EdmsTemplateDocTypeOption[] = [];

    // 1. Canonical template document type options resolved against live categories/types
    for (const baseOpt of EDMS_TEMPLATE_DOC_TYPE_OPTIONS) {
        const liveType = EDMS_DEMO_DOCUMENT_TYPES.find(
            (dt) => dt.typeName.toLowerCase() === baseOpt.value.toLowerCase()
        );
        const liveCat = liveType
            ? EDMS_DEMO_CATEGORIES.find((cat) => cat.id === liveType.categoryId)
            : EDMS_DEMO_CATEGORIES.find((cat) => cat.categoryName === baseOpt.categoryAr);

        const resolvedCategory =
            liveCat?.categoryName || liveType?.categoryName || baseOpt.categoryAr;

        seen.add(baseOpt.value.toLowerCase());
        result.push({
            ...baseOpt,
            categoryAr: resolvedCategory,
            categoryEn: resolvedCategory,
        });
    }

    // 2. Any additional / newly created document types from EDMS_DEMO_DOCUMENT_TYPES
    for (const dt of EDMS_DEMO_DOCUMENT_TYPES) {
        const key = dt.typeName.toLowerCase();
        if (!seen.has(key)) {
            seen.add(key);
            const liveCat = EDMS_DEMO_CATEGORIES.find((cat) => cat.id === dt.categoryId);
            const resolvedCategory = liveCat?.categoryName || dt.categoryName || 'منشأت';
            result.push({
                value: dt.typeName,
                labelEn: dt.typeName,
                labelAr: dt.typeName,
                categoryAr: resolvedCategory,
                categoryEn: resolvedCategory,
            });
        }
    }

    return result;
}

// ============================================================================
// EDMS Audit Trail Dataset (28 Coherent EDMS Audit Records)
// ============================================================================

export type EdmsAuditAction = 'Create' | 'Update' | 'Re-Activated' | 'De-Activated' | 'Delete';

export type EdmsAuditResource =
    | 'Document Type'
    | 'Document Template'
    | 'Employee Template'
    | 'Company Template';

export const EDMS_AUDIT_ACTIONS: EdmsAuditAction[] = [
    'Create',
    'Update',
    'Re-Activated',
    'De-Activated',
    'Delete',
];

export interface EdmsAuditEmployeeOption {
    value: string;
    labelEn: string;
    labelAr: string;
    initials: string;
}

export const EDMS_AUDIT_EMPLOYEES: EdmsAuditEmployeeOption[] = [
    {
        value: 'Emad Alhakami',
        labelEn: 'Emad Alhakami',
        labelAr: 'عماد الحكمي',
        initials: 'EA',
    },
    {
        value: 'Khalifah Alsharabi',
        labelEn: 'Khalifah Alsharabi',
        labelAr: 'خليفة الشرعبي',
        initials: 'KA',
    },
    {
        value: 'Sultan Al-Harbi',
        labelEn: 'Sultan Al-Harbi',
        labelAr: 'سلطان الحربي',
        initials: 'SA',
    },
    {
        value: 'Noura Al-Qahtani',
        labelEn: 'Noura Al-Qahtani',
        labelAr: 'نورة القحطاني',
        initials: 'NQ',
    },
    {
        value: 'Fahad Al-Dosari',
        labelEn: 'Fahad Al-Dosari',
        labelAr: 'فهد الدوسري',
        initials: 'FD',
    },
];

export interface EdmsAuditRecord {
    id: string;
    actionPerformed: EdmsAuditAction;
    resource: EdmsAuditResource;
    resourceData: string;
    performedByEn: string;
    performedByAr: string;
    performedByInitials: string;
    dateTimeDisplay: string;
    isoDate: string;
}

export const EDMS_DEMO_AUDIT_LOGS: EdmsAuditRecord[] = [
    {
        id: 'edms-aud-01',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'طباعة شهادة',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '29/09/2026, 11:18',
        isoDate: '2026-09-29',
    },
    {
        id: 'edms-aud-02',
        actionPerformed: 'Update',
        resource: 'Document Template',
        resourceData: 'طباعة شهاداة',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '28/09/2026, 09:59',
        isoDate: '2026-09-28',
    },
    {
        id: 'edms-aud-03',
        actionPerformed: 'Create',
        resource: 'Document Template',
        resourceData: 'طباعة شهاداة',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '28/09/2026, 09:54',
        isoDate: '2026-09-28',
    },
    {
        id: 'edms-aud-04',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'شهادة',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '28/09/2026, 09:53',
        isoDate: '2026-09-28',
    },
    {
        id: 'edms-aud-05',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'Test Workflow Communication',
        performedByEn: 'Khalifah Alsharabi',
        performedByAr: 'خليفة الشرعبي',
        performedByInitials: 'KA',
        dateTimeDisplay: '14/09/2026, 17:00',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-06',
        actionPerformed: 'Create',
        resource: 'Employee Template',
        resourceData: 'Passport',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 16:19',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-07',
        actionPerformed: 'Create',
        resource: 'Employee Template',
        resourceData: 'Employee Health Insurance',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 16:19',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-08',
        actionPerformed: 'Create',
        resource: 'Employee Template',
        resourceData: 'Employee Contract',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 16:19',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-09',
        actionPerformed: 'Update',
        resource: 'Employee Template',
        resourceData: 'Iqama',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 16:19',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-10',
        actionPerformed: 'Create',
        resource: 'Company Template',
        resourceData: 'SPL Subscription',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 16:13',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-11',
        actionPerformed: 'Create',
        resource: 'Company Template',
        resourceData: 'Commercial Registration',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 15:48',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-12',
        actionPerformed: 'Create',
        resource: 'Company Template',
        resourceData: 'Baladi License',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '14/09/2026, 15:42',
        isoDate: '2026-09-14',
    },
    {
        id: 'edms-aud-13',
        actionPerformed: 'Update',
        resource: 'Company Template',
        resourceData: 'GOSI Subscription',
        performedByEn: 'Sultan Al-Harbi',
        performedByAr: 'سلطان الحربي',
        performedByInitials: 'SA',
        dateTimeDisplay: '12/09/2026, 14:25',
        isoDate: '2026-09-12',
    },
    {
        id: 'edms-aud-14',
        actionPerformed: 'Create',
        resource: 'Company Template',
        resourceData: 'Business Health Insurance',
        performedByEn: 'Noura Al-Qahtani',
        performedByAr: 'نورة القحطاني',
        performedByInitials: 'NQ',
        dateTimeDisplay: '12/09/2026, 11:30',
        isoDate: '2026-09-12',
    },
    {
        id: 'edms-aud-15',
        actionPerformed: 'Create',
        resource: 'Document Template',
        resourceData: 'Vehicle Registration',
        performedByEn: 'Fahad Al-Dosari',
        performedByAr: 'فهد الدوسري',
        performedByInitials: 'FD',
        dateTimeDisplay: '10/09/2026, 13:15',
        isoDate: '2026-09-10',
    },
    {
        id: 'edms-aud-16',
        actionPerformed: 'Create',
        resource: 'Document Template',
        resourceData: 'Vehicle Operation Card',
        performedByEn: 'Fahad Al-Dosari',
        performedByAr: 'فهد الدوسري',
        performedByInitials: 'FD',
        dateTimeDisplay: '10/09/2026, 13:10',
        isoDate: '2026-09-10',
    },
    {
        id: 'edms-aud-17',
        actionPerformed: 'Update',
        resource: 'Document Template',
        resourceData: 'Vehicle Insurance',
        performedByEn: 'Fahad Al-Dosari',
        performedByAr: 'فهد الدوسري',
        performedByInitials: 'FD',
        dateTimeDisplay: '09/09/2026, 16:05',
        isoDate: '2026-09-09',
    },
    {
        id: 'edms-aud-18',
        actionPerformed: 'De-Activated',
        resource: 'Document Template',
        resourceData: 'Legacy Municipal Permit',
        performedByEn: 'Khalifah Alsharabi',
        performedByAr: 'خليفة الشرعبي',
        performedByInitials: 'KA',
        dateTimeDisplay: '08/09/2026, 12:40',
        isoDate: '2026-09-08',
    },
    {
        id: 'edms-aud-19',
        actionPerformed: 'Re-Activated',
        resource: 'Company Template',
        resourceData: 'National Address',
        performedByEn: 'Sultan Al-Harbi',
        performedByAr: 'سلطان الحربي',
        performedByInitials: 'SA',
        dateTimeDisplay: '07/09/2026, 10:22',
        isoDate: '2026-09-07',
    },
    {
        id: 'edms-aud-20',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'تسجيل المركبات',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '06/09/2026, 15:18',
        isoDate: '2026-09-06',
    },
    {
        id: 'edms-aud-21',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'كرت التشغيل المركبات',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '06/09/2026, 15:12',
        isoDate: '2026-09-06',
    },
    {
        id: 'edms-aud-22',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'تامين المركبات',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '06/09/2026, 15:05',
        isoDate: '2026-09-06',
    },
    {
        id: 'edms-aud-23',
        actionPerformed: 'Update',
        resource: 'Employee Template',
        resourceData: 'Re entry Visa',
        performedByEn: 'Noura Al-Qahtani',
        performedByAr: 'نورة القحطاني',
        performedByInitials: 'NQ',
        dateTimeDisplay: '04/09/2026, 11:45',
        isoDate: '2026-09-04',
    },
    {
        id: 'edms-aud-24',
        actionPerformed: 'Create',
        resource: 'Employee Template',
        resourceData: 'Final Exit Visa',
        performedByEn: 'Noura Al-Qahtani',
        performedByAr: 'نورة القحطاني',
        performedByInitials: 'NQ',
        dateTimeDisplay: '04/09/2026, 11:30',
        isoDate: '2026-09-04',
    },
    {
        id: 'edms-aud-25',
        actionPerformed: 'Delete',
        resource: 'Document Type',
        resourceData: 'Draft Temporary Permit',
        performedByEn: 'Khalifah Alsharabi',
        performedByAr: 'خليفة الشرعبي',
        performedByInitials: 'KA',
        dateTimeDisplay: '03/09/2026, 14:50',
        isoDate: '2026-09-03',
    },
    {
        id: 'edms-aud-26',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'اشتراك قوى للمنشات',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '02/09/2026, 10:15',
        isoDate: '2026-09-02',
    },
    {
        id: 'edms-aud-27',
        actionPerformed: 'Create',
        resource: 'Document Type',
        resourceData: 'اشتراك مدد للمنشات',
        performedByEn: 'Emad Alhakami',
        performedByAr: 'عماد الحكمي',
        performedByInitials: 'EA',
        dateTimeDisplay: '02/09/2026, 10:08',
        isoDate: '2026-09-02',
    },
    {
        id: 'edms-aud-28',
        actionPerformed: 'Create',
        resource: 'Company Template',
        resourceData: 'Qiwa Subscription',
        performedByEn: 'Sultan Al-Harbi',
        performedByAr: 'سلطان الحربي',
        performedByInitials: 'SA',
        dateTimeDisplay: '01/09/2026, 09:30',
        isoDate: '2026-09-01',
    },
];


